services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ~/volumes/mohamedhedi1/postgresql/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mohamedhedi1
      - POSTGRES_USER=mohamedhedi1
    ports:
      - 127.0.0.1:5432:5432
