version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ~/volumes/mohamedhedi1/postgresql/:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=mohamedhedi1
      - POSTGRES_USER=mohamedhedi1
      - POSTGRES_DB=whatsappclone
    ports:
      - 127.0.0.1:5432:5432
